global:
  scrape_interval:     15s

  external_labels:
    monitor: 'game-service-monitor'

scrape_configs:
- job_name: 'game-service'
  scrape_interval: 5s
  metrics_path: '/metrics/'
  static_configs:
  - targets: ['host.docker.internal:9080']
  scheme: http
  tls_config:
    insecure_skip_verify: true
- job_name: 'player-service'
  scrape_interval: 5s
  metrics_path: '/metrics/'
  static_configs:
  - targets: ['host.docker.internal:8081']
  scheme: http
  tls_config:
    insecure_skip_verify: true
- job_name: 'auth-service'
  scrape_interval: 5s
  metrics_path: '/metrics/'
  static_configs:
  - targets: ['host.docker.internal:8082']
  scheme: http
  tls_config:
    insecure_skip_verify: true
- job_name: 'frontend'
  scrape_interval: 5s
  metrics_path: '/metrics/'
  static_configs:
  - targets: ['host.docker.internal:12000']
  scheme: http
  tls_config:
    insecure_skip_verify: true